[package]
name = "polytechnique-reports"
version = "0.1.0"
entrypoint = "polytechnique.typ"
authors = ["Rémi Germe <@remigerme>"]
license = "MIT"
description = "A report template for Polytechnique students."
repository = "https://github.com/remigerme/typst-polytechnique"
keywords = ["polytechnique", "école polytechnique", "report", "rapport", "stage"]
categories = ["report"]
exclude = [
    ".gitignore",
    "guide.typ", "guide.pdf",
    "assets/example.bib",
    "assets/logo-x.eps", "assets/logo-x-ip-paris.eps",
    "assets/armes.eps", "assets/filet-court.eps", "assets/filet-long.eps"
]

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "report-thumbnail.png"
