[package]
name = "monash-university-report"
version = "0.2.0"
authors = ["Xingyu Yang <xyan0147@student.monash.edu>"]
license = "MIT"
description = "A report/assignment template for Monash University students with official brand colors and theorem environments."
repository = "https://github.com/Eryc123Y/typst-report-monash"
keywords = ["monash", "university", "report", "assignment", "education", "theorem", "mathematics"]
categories = ["Paper", "Text", "Report"]
homepage = "https://github.com/your-username/typst-report-monash"
documentation = "https://github.com/your-username/typst-report-monash/blob/main/README.md"
compiler = "0.12.0"
exclude = [
    ".gitignore",
    "guide.typ", "guide.pdf",
    "assets/example.bib", "assets/typst.png",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/thumbnail.png"