[package]
name = "monash-university-report"
version = "0.1.0"
entrypoint = "monash-report.typ"
authors = ["Eric <@eric>"]
license = "MIT"
description = "A professional report template for Monash University students with official brand colors."
repository = "https://github.com/eric/typst-report-monash"
keywords = ["monash", "university", "report", "assignment", "education", "thesis"]
categories = ["report"]
exclude = [
    ".gitignore",
    "guide.typ", "guide.pdf",
    "assets/example.bib", "assets/typst.png",
]

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "report-thumbnail.png"
